### ISSUE TITLE
admin 后台管理无法登陆，登陆不跳转

### ISSUE THREAD

**Issue by Benson-QAQ** [ghostxbh/uzy-ssm-mall#10]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ghostxbh** [comment]
前端JS文件原因，未修复

**Comment by 763kkk** [comment]
> 前端JS文件原因，未修复

你好，请问现在修复了吗？想求一个

**Comment by pybgithub1** [comment]
后台管理系统登录不了

**Comment by N0boy-0** [comment]
`        $.ajax({
            url: "/mall/admin/login/doLogin",
            type:"post",
            data: {"username":username,"password":password},
            dataType: "json",
            async:false,
            success:function (data) {
                $("#btn_login").val("登录");
                if (data.success) {
                    cookieUtil.setCookie("username", username, 30);
                    window.location.href = "/mall/admin";
                    window.event.returnValue = false;
                } else {
                    styleUtil.errorShow($("#txt_error_msg"), "用户名或密码错误");
                }
            },
            beforeSend:function () {
                $("#btn_login").val("登录中...");
            },
            error:function (data) {
            }
        });`
将src/main/webapp/static/js/admin/admin_login.js 中ajax中的代码替换为这一段，就可以正常跳转了
